### ISSUE TITLE
Integer-valued operators

### ISSUE THREAD

**Issue by quattro** [google/lineax#27]
Hi all, I'm super excited to start using the new lineax library to re-implement some of my own linear operator functionality in statistical genetics. We commonly use integer valued matrices to represent genotype data (0/1/2) and can represent a centered/scaled genotype matrix as a linear operator (I'll skip details for now). Currently, lineax enforces float-valued operators, as examplified by

```python
        if not jnp.issubdtype(matrix, jnp.inexact):
            matrix = matrix.astype(jnp.float32)
```

Is there room for either an Int operator, or to use generic types to generalize the matrix operator by underlying numeric type?

**Comment by patrick-kidger** [comment]
Hmm, that is -- you want to solve an $Ax = b$ problem where both $A$ and $b$ are integers, and the construction of the problem is such that $x$ is known to have an integer value as well?

What kind of linear solver are you currently using to solve this?

**Comment by quattro** [comment]
Hi @patrick-kidger , I'm not suggesting that `b` must be integer, only `A`. Without going into too much detail, this is related to space/memory, where we can use small integer representation (e.g., int8), since we only need to cover 3 values (which can be further improved by leveraging sparsity of the 0s).

**Comment by patrick-kidger** [comment]
Ah, you're primarily just interested in representing the linear operator, not using it to solve a linear system? You could do that like this, then:
```python
import equinox as eqx
import jax
import jax.experimental.sparse as js
import jax.numpy as jnp
import lineax as lx


class SparseQuantisedOperator(lx.AbstractLinearOperator):
    matrix: js.BCOO

    def mv(self, vector):
        return js.sparsify(lambda m, v: m @ v)(self.matrix, vector)

    def as_matrix(self):
        raise ValueError("Refusing to materialise sparse matrix.")
        # Or you could do:
        # return self.matrix.todense()

    def transpose(self):
        return SparseQuantisedOperator(self.matrix.T)

    def in_structure(self):
        _, in_size = self.matrix.shape
        return jax.ShapeDtypeStruct((in_size,), jnp.float32)

    def out_structure(self):
        out_size, _ = self.matrix.shape
        return jax.ShapeDtypeStruct((out_size,), jnp.float32)

#
# Example usage: solve a linear system.
#

@lx.is_symmetric.register
def _(op: SparseQuantisedOperator):
    return False

@lx.is_negative_semidefinite.register
def _(op: SparseQuantisedOperator):
    return False

@lx.linearise.register
def _(op: SparseQuantisedOperator):
    return op

matrix = js.BCOO.fromdense(jnp.array([[1.0, 0.0], [0.0, 1.0]]))
op = SparseQuantisedOperator(matrix)
sol = lx.linear_solve(op, jnp.array([1., 2.]), solver=lx.NormalCG(rtol=1e-5, atol=1e-5))
print(sol.value)
```

**Comment by patrick-kidger** [comment]
I think probably the generic approach. Otherwise you may have that `operator.matrix.dtype != operator.dtype`; it's generally better to make illegal data structures unrepresentable.
