### ISSUE TITLE
Multivariate linear solver

### ISSUE THREAD

**Issue by quattro** [google/lineax#29]
Hi all, thanks again for developing such an intuitive and useful library! It would be great to have functionality that generalizes solving $Ax = b$ to more general $AX = B$ systems. for matrices $X$, $B$. Likewise for the normal equations $A'AX = A'B$. 

I tried to accomplish this by naive use of the API and received shape errors. 

```
Vector and operator structures do not match. Got a vector with structure ShapeDtypeStruct(shape=(50, 100), dtype=float32) and an operator with out-structure ShapeDtypeStruct(shape=(50,), dtype=float32)
```

**Comment by patrick-kidger** [comment]
This should be doable using `jax.vmap`.

**Comment by quattro** [comment]
Fantastic, I'll toy around to get an example up and running. It would be great to have an expanded FAQ or Cookbook for new users.

**Comment by patrick-kidger** [comment]
Agreed! This should go in the FAQ.
(If you wish we'd be happy to take a PR on this.)
