### ISSUE TITLE
a vs _a

### ISSUE THREAD

**Issue by lockwo** [google/lineax#99]
In the docs, `mv` uses `_a` but as matrix uses `a`. Are these meaningfully different parameters or could they be made the same?

<img width="861" alt="Screenshot 2024-06-04 at 9 17 28 AM" src="https://github.com/patrick-kidger/lineax/assets/42878312/ac790469-4521-415f-b6ef-d137630ce290">

**Comment by patrick-kidger** [comment]
The underscore means that it is not checked. This reflects the fact that it's in a `PyTree`, and different nodes in the PyTree need not have the exact same sizes.
